### ISSUE TITLE
Create MySQL Script for Plant Monitor project

### ISSUE THREAD

**Issue by joesan** [joesan/database-projects#2]
Have a look here. This is the SQL script for H2 database. 

https://github.com/joesan/database-projects/tree/master/power-plant-monitor/h2/scripts/database

I need another script for the MySQL database.

As a reference have a look at this script here:

https://github.com/joesan/database-projects/tree/master/power-plant-simulator/mysql

**Comment by mahadetech** [comment]
I have implemented the script. @joesan please take a look!
